name: Build

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Download Capstone
        run: |
          curl -L https://github.com/capstone-engine/capstone/releases/download/5.0.1/capstone-5.0.1-win64.zip -o capstone.zip
          tar -xf capstone.zip
          ren capstone-5.0.1-win64 capstone

      - name: Configure
        run: cmake -B build -S .

      - name: Build
        run: cmake --build build --config Release
